### ISSUE TITLE
bug in eval-correlation.py

### ISSUE THREAD

**Issue by 17687473441** [megagonlabs/llm-longeval#1]
I want to ask if the field indicated in the graph at line 39 of the eval-correlation.py file is written incorrectly. The original text says that there is no such field as factual_consistency when running, and I changed it to the one shown in the next graph to run normally. Does this affect the results of the operation?

![微信图片_20240921145059](https://github.com/user-attachments/assets/3a68e9df-5068-4199-9103-0a9d039a1cf0)

**Comment by isomap** [comment]
sorry for the late response. i guess you are right. i believe the results should still be the same with those changes, but please note that the gpt-4 model, which we used in our experiments, is quite expensive compared to the current sota models like gpt4o or o1. i believe gpt4o-mini might show better results and >100x cheaper than the original gpt4, so you can consider using it instead if you want to apply our method to your application :)

**Comment by 17687473441** [comment]
你好，我正忙中，无法亲自回复你的邮件。我将在忙完结束后，尽快给你回复。

**Comment by isomap** [comment]
理解 😃
